[env:nodemcu-32s]
platform = https://github.com/tasmota/platform-espressif32/releases/download/2024.12.30/platform-espressif32.zip
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
build_flags =
    -D LWIP_FEATURES=1
    -D LWIP_IPV4=1
    -D IP_NAPT=1
